package com.mbem.immocam.shared.enums;

/**
 * Types d'actions enregistrees dans les logs d'activite.
 */
public enum TypeAction {
    // Auth
    CONNEXION, DECONNEXION, INSCRIPTION, VALIDATION_EMAIL,
    REINITIALISATION_MDP, TENTATIVE_CONNEXION_ECHOUEE, COMPTE_BLOQUE,
    // Annonces
    PUBLICATION_ANNONCE, MODIFICATION_ANNONCE, PAUSE_ANNONCE,
    REACTIVATION_ANNONCE, RENOUVELLEMENT_ANNONCE, ARCHIVAGE_ANNONCE,
    SUPPRESSION_ANNONCE, EXPIRATION_ANNONCE, SUPPRESSION_SYSTEME_ANNONCE,
    // Photos
    UPLOAD_PHOTO, SUPPRESSION_PHOTO,
    // Contact
    CONTACT_WHATSAPP,
    // Favoris
    AJOUT_FAVORI, SUPPRESSION_FAVORI,
    // Commentaires
    COMMENTAIRE_PUBLIE, REPONSE_COMMENTAIRE, SUPPRESSION_COMMENTAIRE,
    // Signalements
    SIGNALEMENT_SOUMIS, SIGNALEMENT_TRAITE,
    // Admin
    SUSPENSION_UTILISATEUR, BANNISSEMENT_UTILISATEUR, REACTIVATION_UTILISATEUR,
    SUPPRESSION_ANNONCE_ADMIN, MODIFICATION_CONFIG_SYSTEME,
    AJOUT_VILLE, AJOUT_TYPE_BIEN, SAUVEGARDE_BASE
}
